## Operator
operator:
  # Name that will be assigned to most of internal Kubernetes objects like
  # Deployment, ServiceAccount, Role etc.
  name: mongodb-kubernetes-operator

  # Name of the operator image
  operatorImageName: mongodb-kubernetes-operator

  # Name of the deployment of the operator pod
  deploymentName: mongodb-kubernetes-operator

  # Version of mongodb-kubernetes-operator
  version: latest

  # Uncomment this line to watch all namespaces
  watchNamespace: "*"

  # Resources allocated to Operator Pod
  resources:
    limits:
      cpu: 1100m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 200Mi

  # Additional environment variables
  extraEnvs: [ ]
  # environment:
  # - name: CLUSTER_DOMAIN
  #   value: my-cluster.domain

## Operator's database
database:
  name: mongodb-database
  namespace: mongodb

agent:
  name: mongodb-agent
  version: 11.12.0.7388-1
versionUpgradeHook:
  name: mongodb-kubernetes-operator-version-upgrade-post-start-hook
  version: 1.0.4
readinessProbe:
  name: mongodb-kubernetes-readinessprobe
  version: 1.0.8
mongodb:
  name: mongo


pullPolicy: IfNotPresent

registry:
  agent: docker.io/jinchengsix
  versionUpgradeHook: docker.io/jinchengsix
  readinessProbe: docker.io/jinchengsix
  operator: docker.io/jinchengsix
  mongodb: docker.io/jinchengsix

# Set to false if CRDs have been installed already. The CRDs can be installed
# manually from the code repo: github.com/mongodb/mongodb-kubernetes-operator or
# using the `community-operator-crds` Helm chart.
community-operator-crds:
  enabled: true

# Deploys MongoDB with `resource` attributes.
createResource: false

# 判断当前动作是更新还是创建 [create,update,delete]
action: create

resource:
  name: mongodb
  version: 4.2.19
  members: 3
  tls:
    enabled: false

    # Installs Cert-Manager in this cluster.
    useCertManager: true
    certificateKeySecretRef: tls-certificate
    caCertificateSecretRef: tls-ca-key-pair
    certManager:
      certDuration: 8760h   # 365 days
      renewCertBefore: 720h   # 30 days
  prometheus:
    enabled: true # 是否开启 promethus, true(default) or false
    username: prometheus
    password: prometheus
    metricsPath: /metrics
    port: 9216
    tlsSecretKeyRef:
  users:
    username: shuaib
    password: zhu1241jie

  additionalMongodConfig:
    oplogSizeMB: 10240
    port: 27017

  statefulSet:
    mongod:
      cpu: 2
      memory: 2G
    agent:
      cpu: 0.2
      memory: 200M
    volumeClaimTemplates:
      storage: 100Gi

