apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ .Values.database.namespace }}  # database namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWIucWluZ2Nsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImNoZW54aW4iLCJwYXNzd29yZCI6Ilhpb25nMDMyMSIsImF1dGgiOiJZMmhsYm5ocGJqcFlhVzl1WnpBek1qRT0ifX19

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ .Release.Namespace }} # operator namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXJodWIucWluZ2Nsb3VkLmNvbSI6eyJ1c2VybmFtZSI6ImNoZW54aW4iLCJwYXNzd29yZCI6Ilhpb25nMDMyMSIsImF1dGgiOiJZMmhsYm5ocGJqcFlhVzl1WnpBek1qRT0ifX19
