{{ if .Values.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secretName }}
  namespace: {{ .Release.Namespace }} # operator namespace
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.registry.secret }}
{{ end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-endpoint-password
type: Opaque
stringData:
  password: promethus
